apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/rotem-repo:wordpress
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          value: db
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name:  wordpress-secret
              key: mysql-password
        - name: WORDPRESS_DB_NAME
          value: wordpress
        volumeMounts:
        - name: wp-data
          mountPath: /var/www/html
      imagePullSecrets:
      - name: ecr-creds
      volumes:
      - name: wp-data
        persistentVolumeClaim:
          claimName: wordpress-data
